dist: trusty
sudo: false
language: go
go:
- 1.8
install:
- make change-import-path
- bash scripts/gogetcookie.sh
- go get github.com/kardianos/govendor
script:
- make vet vendor-status test
- go build
